stages:
- name: Compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: pushcommerce/helloworld:${CICD_GIT_COMMIT}
      pushRemote: true
      registry: index.docker.io
- name: Publish
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
