steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/helloworld-app:$SHORT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/helloworld-app', 'helloworld-app=gcr.io/$PROJECT_ID/helloworld-app:$SHORT_SHA']
images:
- 'gcr.io/$PROJECT_ID/helloworld-app'
